# Generated by Django 4.2.7 on 2025-09-26 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_admininviteotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='can_login',
            field=models.BooleanField(default=False, help_text='Admin-granted permission. If true, student can log in.'),
        ),
    ]
