# Generated by Django 4.2.7 on 2025-11-25 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_student_can_login"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_path",
                    models.CharField(
                        help_text="Relative path from MEDIA_ROOT", max_length=500
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "frame_number",
                    models.IntegerField(help_text="Frame sequence number from video"),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frames",
                        to="accounts.student",
                    ),
                ),
            ],
            options={
                "ordering": ["student", "frame_number"],
            },
        ),
    ]
