# Generated by Django 4.2.7 on 2025-11-25 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_studentframe"),
        ("attendance", "0002_classroom_session_class_room"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_path",
                    models.CharField(
                        help_text="Relative path from MEDIA_ROOT", max_length=500
                    ),
                ),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "frame_number",
                    models.IntegerField(help_text="Frame sequence during session"),
                ),
                (
                    "recognized_students",
                    models.ManyToManyField(
                        blank=True,
                        related_name="recognized_in_frames",
                        to="accounts.student",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="captured_frames",
                        to="attendance.session",
                    ),
                ),
            ],
            options={
                "ordering": ["session", "frame_number"],
            },
        ),
    ]
