# Generated by Django 4.2.7 on 2025-12-08 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_sessionframe"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimeTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        help_text="Day of the week",
                    ),
                ),
                (
                    "session_name",
                    models.CharField(
                        help_text="Subject or session name (e.g., Math, Physics)",
                        max_length=100,
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(help_text="Session start time (e.g., 09:00)"),
                ),
                (
                    "end_time",
                    models.TimeField(help_text="Session end time (e.g., 10:00)"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Enable/disable this timetable entry"
                    ),
                ),
                (
                    "class_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timetable_entries",
                        to="attendance.classroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "TimeTable Entry",
                "verbose_name_plural": "TimeTable",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
    ]
