# Generated by Django 4.2.7 on 2025-12-09 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_timetable"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="timetable_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_sessions",
                to="attendance.timetable",
            ),
        ),
    ]
