# Generated by Django 4.2.7 on 2026-01-21 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_session_timetable_entry"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Configuration key (e.g., camera_source)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("value", models.TextField(help_text="Configuration value")),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of what this setting does"
                    ),
                ),
            ],
        ),
    ]
